Repository The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool, pull requests merged in 2022-09, with the labels that each got.

#144 added missing lastRun registry functionality
  Windows_VDOT.ps1
Labels: Code Fix

#145 Spelling and markdown fixes
  2009/README.md
  VersionInfo.md
Labels: documentation

#147 Set Edge Efficiency mode to always on
  2009/ConfigurationFiles/EdgeSettings.json
Labels: Under Review
